# Generated by Django 2.2.7 on 2019-11-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mailinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
    ]
