# Generated by Django 2.2.6 on 2019-11-16 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mailinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='users_registered',
            field=models.ManyToManyField(related_name='events_registered_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
