# Generated by Django 2.2.7 on 2019-11-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191116_2247'),
        ('api', '0005_auto_20191118_2143'),
    ]

    operations = [
    ]
